services:
  postgres:
    container_name: bot-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=991fa522db6ddb9935c7d9b1
      - POSTGRES_DB=bot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: bot-redis
    image: redis:latest
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  postgres_data:
  redis_data:
